### ISSUE TITLE
Only obtaining coordinates and time stamps

### ISSUE THREAD

**Issue by albinahlback** [JoonasVali/NaturalMouseMotion#17]
Is it possible to only get coordinates along with time stamps for each coordinates? I am not interested in any interaction with the OS here.

I asked a similar question here: https://github.com/barrybingo/CNaturalMouseMotion/issues/3.

**Comment by JoonasVali** [comment]
Yes, it's possible, you need to write your own `SystemCalls` and `MouseInfoAccessor` interface implementation as described here:

https://github.com/JoonasVali/NaturalMouseMotion?tab=readme-ov-file#what-if-i-want-to-move-something-else-than-a-mouse-on-something-else-than-a-screen

Basically just pretend that the mouse is moving by not calling the Robot class, and write out the coordinates and timestamps as needed.

You need to simulate the mouse movement in `MouseInfoAccessor` virtually, otherwise the library will think the mouse is not moving. So what ever is written in `SystemCalls`, must also be accessible from `MouseInfoAccessor`.
